# Generated by Django 5.2.17 on 2026-09-28 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FloatingButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to hide on the website.')),
                ('button_type', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('phone', 'Phone call'), ('custom', 'Custom link')], max_length=20)),
                ('label', models.CharField(help_text='Tooltip / accessibility text.', max_length=50)),
                ('link', models.CharField(blank=True, help_text='Leave empty to use the WhatsApp / email / phone from Site Settings.', max_length=255)),
                ('icon', models.ImageField(blank=True, help_text='Optional. Leave empty to use the built-in icon.', null=True, upload_to='floating/')),
                ('open_in_new_tab', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Floating button',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_line_1', models.CharField(help_text='First line, e.g. "Global Tamil"', max_length=100)),
                ('title_highlight', models.CharField(blank=True, help_text='Second line in yellow, e.g. "University"', max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('button_text', models.CharField(blank=True, max_length=50)),
                ('button_link', models.CharField(blank=True, max_length=255)),
                ('background_image', models.ImageField(blank=True, help_text='Recommended 1920×1080 or larger.', null=True, upload_to='hero/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Section',
            },
        ),
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cta_text', models.CharField(blank=True, max_length=50, verbose_name='Button text')),
                ('cta_link', models.CharField(blank=True, help_text='e.g. #admissions or a full URL', max_length=255, verbose_name='Button link')),
                ('is_sticky', models.BooleanField(default=True, help_text='Keep the navbar fixed at the top while scrolling.')),
            ],
            options={
                'verbose_name': 'Navbar',
                'verbose_name_plural': 'Navbar',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(help_text='Browser tab title (max ~60–70 chars).', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='Shown in Google results (max ~160 chars).', max_length=300)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma separated.', max_length=300)),
                ('og_image', models.ImageField(blank=True, help_text='Preview image when the link is shared (1200×630).', null=True, upload_to='seo/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('university_name', models.CharField(max_length=100)),
                ('established_text', models.CharField(blank=True, help_text='e.g. "Est. 2001 · Coimbatore"', max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, help_text='As displayed, e.g. +91 422 123 4567', max_length=30)),
                ('whatsapp_number', models.CharField(blank=True, help_text='Digits with country code, no + or spaces, e.g. 914221234567', max_length=20)),
                ('show_topbar', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Site Settings (SEO, Logo, Contact, Top Bar)',
                'verbose_name_plural': 'Site Settings (SEO, Logo, Contact, Top Bar)',
            },
        ),
        migrations.CreateModel(
            name='HeroTagWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to hide on the website.')),
                ('text', models.CharField(max_length=30)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_words', to='website.herosection')),
            ],
            options={
                'verbose_name': 'Tag word',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NavMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to hide on the website.')),
                ('label', models.CharField(max_length=50)),
                ('link', models.CharField(help_text='Section anchor like #about, or a full URL.', max_length=255)),
                ('open_in_new_tab', models.BooleanField(default=False)),
                ('navbar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='website.navbar')),
            ],
            options={
                'verbose_name': 'Menu item',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
