# Generated by Django 5.2.17 on 2026-09-28 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eyebrow', models.CharField(blank=True, help_text='Yellow text above the title, e.g. "ABOUT GLOBAL TAMIL UNIVERSITY"', max_length=100, verbose_name='Small heading')),
                ('title', models.TextField(help_text='Press Enter to start a new line.', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, help_text='Recommended 1200×700.', null=True, upload_to='about/')),
                ('image_alt', models.CharField(blank=True, help_text='Describe the image (for SEO and screen readers).', max_length=150)),
                ('link_text', models.CharField(blank=True, max_length=50)),
                ('link_url', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Section',
            },
        ),
        migrations.CreateModel(
            name='AboutFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to hide on the website.')),
                ('title', models.CharField(max_length=100)),
                ('icon_class', models.CharField(blank=True, help_text='Font Awesome class, e.g. "fa-solid fa-graduation-cap"', max_length=100)),
                ('icon_image', models.ImageField(blank=True, help_text='Optional. Used instead of the icon class when uploaded.', null=True, upload_to='about/icons/')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='website.aboutsection')),
            ],
            options={
                'verbose_name': 'Feature',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
