# Generated by Django 5.2.17 on 2026-09-28 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_aboutsection_aboutfeature'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eyebrow', models.CharField(blank=True, help_text='Text above the title, e.g. "OUR ACADEMICS"', max_length=100, verbose_name='Small heading')),
                ('title', models.TextField(help_text='Press Enter to start a new line.', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('button_text', models.CharField(blank=True, max_length=50)),
                ('button_link', models.CharField(blank=True, max_length=255)),
                ('background_image', models.ImageField(blank=True, help_text='Faded classroom background. Recommended 1920×1080.', null=True, upload_to='academics/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Academics Section',
                'verbose_name_plural': 'Academics Section',
            },
        ),
        migrations.RemoveField(
            model_name='aboutfeature',
            name='icon_image',
        ),
        migrations.RemoveField(
            model_name='floatingbutton',
            name='icon',
        ),
        migrations.AlterField(
            model_name='aboutfeature',
            name='icon_class',
            field=models.CharField(blank=True, help_text='Font Awesome icon class, e.g. "fa-solid fa-graduation-cap". Browse icons at fontawesome.com/icons (free, solid).', max_length=100),
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to hide on the website.')),
                ('title', models.CharField(max_length=150)),
                ('duration', models.CharField(blank=True, help_text='e.g. "3 Years". Leave empty if not shown.', max_length=50)),
                ('subjects', models.CharField(blank=True, help_text='e.g. "Literature, Linguistics, Classical Tamil"', max_length=255)),
                ('icon_class', models.CharField(blank=True, help_text='Font Awesome icon class, e.g. "fa-solid fa-graduation-cap". Browse icons at fontawesome.com/icons (free, solid).', max_length=100)),
                ('academics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='website.academicssection')),
            ],
            options={
                'verbose_name': 'Program',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
