# Generated by Django 5.2.17 on 2026-09-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_academicssection_remove_aboutfeature_icon_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eyebrow', models.CharField(blank=True, help_text='Text above the title, e.g. "ADMISSIONS"', max_length=100, verbose_name='Small heading')),
                ('title', models.TextField(help_text='Press Enter to start a new line.', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('button_text', models.CharField(blank=True, max_length=50)),
                ('button_link', models.CharField(blank=True, help_text='e.g. "#contact" to scroll to the contact section.', max_length=255)),
                ('image', models.ImageField(blank=True, help_text='Recommended 1200×700.', null=True, upload_to='admissions/')),
                ('image_alt', models.CharField(blank=True, help_text='Describe the image (for SEO and screen readers).', max_length=150)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Admissions Section',
                'verbose_name_plural': 'Admissions Section',
            },
        ),
    ]
