# Generated by Django 5.2.17 on 2026-09-28 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_admissionssection'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eyebrow', models.CharField(blank=True, help_text='e.g. "CURRENT OPENINGS · 2026–27 INTAKE"', max_length=100, verbose_name='Small heading')),
                ('title', models.TextField(help_text='Press Enter to start a new line.', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('apply_button_text', models.CharField(blank=True, default='Apply Now', help_text='Button text on every course row.', max_length=50)),
                ('apply_button_link', models.CharField(blank=True, default='#contact', help_text="Default link for every course row's button.", max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Course Openings Section',
                'verbose_name_plural': 'Course Openings Section',
            },
        ),
        migrations.CreateModel(
            name='CourseOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to hide on the website.')),
                ('level', models.CharField(choices=[('undergraduate', 'Undergraduate'), ('postgraduate', 'Postgraduate'), ('doctoral', 'Doctoral'), ('diploma', 'Diploma')], max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('open', 'Open'), ('filling_fast', 'Filling Fast'), ('closing_soon', 'Closing Soon'), ('closed', 'Closed')], default='open', max_length=20)),
                ('duration', models.CharField(help_text='e.g. "3 years" or "As per research plan"', max_length=50)),
                ('eligibility', models.CharField(max_length=150)),
                ('apply_by', models.DateField(blank=True, help_text='Last date to apply. Shown as e.g. 20 Oct 2026.', null=True)),
                ('apply_link', models.CharField(blank=True, help_text="Leave empty to use the section's default button link.", max_length=255)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='website.openingssection')),
            ],
            options={
                'verbose_name': 'Course opening',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
