# Generated by Django 5.2.17 on 2026-09-28 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_openingssection_courseopening'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchAreasSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eyebrow', models.CharField(blank=True, help_text='e.g. "RESEARCH AREAS"', max_length=100, verbose_name='Small heading')),
                ('title', models.TextField(help_text='Press Enter to start a new line.', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Research Areas Section',
                'verbose_name_plural': 'Research Areas Section',
            },
        ),
        migrations.CreateModel(
            name='ResearchSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eyebrow', models.CharField(blank=True, help_text='e.g. "RESEARCH AT GTU"', max_length=100, verbose_name='Small heading')),
                ('title', models.TextField(help_text='Press Enter to start a new line.', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('highlight_label', models.CharField(blank=True, help_text='e.g. "RESEARCH HIGHLIGHT"', max_length=100, verbose_name='Label')),
                ('highlight_title', models.CharField(blank=True, max_length=200, verbose_name='Title')),
                ('highlight_description', models.TextField(blank=True, verbose_name='Description')),
                ('highlight_image', models.ImageField(blank=True, help_text='Large image. Recommended 1400×900.', null=True, upload_to='research/', verbose_name='Image')),
                ('highlight_image_alt', models.CharField(blank=True, max_length=150, verbose_name='Image alt text')),
                ('side_label', models.CharField(blank=True, help_text='e.g. "FACULTY RESEARCH"', max_length=100, verbose_name='Label')),
                ('side_title', models.CharField(blank=True, max_length=200, verbose_name='Title')),
                ('side_description', models.TextField(blank=True, verbose_name='Description')),
                ('side_image', models.ImageField(blank=True, help_text='Recommended 900×650.', null=True, upload_to='research/', verbose_name='Image')),
                ('side_image_alt', models.CharField(blank=True, max_length=150, verbose_name='Image alt text')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Research Section',
                'verbose_name_plural': 'Research Section',
            },
        ),
        migrations.AlterModelOptions(
            name='courseopening',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses (Course Openings list)'},
        ),
        migrations.AddField(
            model_name='openingssection',
            name='footnote',
            field=models.CharField(blank=True, help_text='Small note shown below the course list.', max_length=300),
        ),
        migrations.AlterField(
            model_name='aboutfeature',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers show first. Leave 0 to add at the end.'),
        ),
        migrations.AlterField(
            model_name='courseopening',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers show first. Leave 0 to add at the end.'),
        ),
        migrations.AlterField(
            model_name='floatingbutton',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers show first. Leave 0 to add at the end.'),
        ),
        migrations.AlterField(
            model_name='herotagword',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers show first. Leave 0 to add at the end.'),
        ),
        migrations.AlterField(
            model_name='navmenuitem',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers show first. Leave 0 to add at the end.'),
        ),
        migrations.AlterField(
            model_name='program',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers show first. Leave 0 to add at the end.'),
        ),
        migrations.CreateModel(
            name='ResearchFocus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first. Leave 0 to add at the end.')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to hide on the website.')),
                ('label', models.CharField(help_text='e.g. "CURRENT RESEARCH PROJECTS" (number is added automatically)', max_length=100)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_items', to='website.researchareassection')),
            ],
            options={
                'verbose_name': 'Focus item',
                'verbose_name_plural': 'Focus items',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResearchTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first. Leave 0 to add at the end.')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to hide on the website.')),
                ('name', models.CharField(max_length=60)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='website.researchareassection')),
            ],
            options={
                'verbose_name': 'Tag',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
