# Generated by Django 5.2.17 on 2026-09-28 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_researchareassection_researchsection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eyebrow', models.CharField(blank=True, help_text='e.g. "OUR CAMPUS"', max_length=100, verbose_name='Small heading')),
                ('title', models.TextField(help_text='Press Enter to start a new line.', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('button_text', models.CharField(blank=True, max_length=50)),
                ('button_link', models.CharField(blank=True, help_text='e.g. "#gallery" to scroll to the gallery section.', max_length=255)),
                ('image', models.ImageField(blank=True, help_text='Recommended 1400×800.', null=True, upload_to='campus/')),
                ('image_alt', models.CharField(blank=True, help_text='Describe the image (for SEO and screen readers).', max_length=150)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Campus Section',
                'verbose_name_plural': 'Campus Section',
            },
        ),
        migrations.CreateModel(
            name='CampusFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first. Leave 0 to add at the end.')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to hide on the website.')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='website.campussection')),
            ],
            options={
                'verbose_name': 'Facility',
                'verbose_name_plural': 'Facilities',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
