# Generated by Django 5.2.17 on 2026-09-28 06:17

import django.db.models.deletion
import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_campussection_campusfacility'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first. Leave 0 to add at the end.')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to hide on the website.')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, help_text='Used by the filter buttons. Filled automatically from the name.', max_length=60, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GallerySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eyebrow', models.CharField(blank=True, help_text='e.g. "COLLEGE GALLERY"', max_length=100, verbose_name='Small heading')),
                ('title', models.TextField(help_text='Press Enter to start a new line.', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('show_filters', models.BooleanField(default=True, help_text='Show the category filter buttons above the photos.')),
                ('all_filter_label', models.CharField(default='All', help_text='Text of the first filter button.', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Gallery Section',
                'verbose_name_plural': 'Gallery Section',
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first. Leave 0 to add at the end.')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to hide on the website.')),
                ('title', models.CharField(help_text='White caption on the photo, e.g. "Learning together"', max_length=150)),
                ('image', models.ImageField(blank=True, help_text='Saved as gallery/<category>/<title>. Large photos are compressed automatically.', null=True, upload_to=website.models.gallery_upload_to)),
                ('alt_text', models.CharField(blank=True, help_text='Describe what is in the photo (SEO & screen readers). Leave empty to create it from the title and category.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional longer description (shown when the photo is opened).')),
                ('size', models.CharField(choices=[('normal', 'Normal (1 column)'), ('wide', 'Wide (2 columns)'), ('tall', 'Tall (2 rows)'), ('full', 'Full width (whole row)')], default='normal', help_text='How much space the photo takes in the grid.', max_length=10)),
                ('category', models.ForeignKey(blank=True, help_text='Yellow label on the photo and filter group.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='website.gallerycategory')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='website.gallerysection')),
            ],
            options={
                'verbose_name': 'Gallery photo',
                'verbose_name_plural': 'Gallery photos',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='gallerycategory',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='website.gallerysection'),
        ),
    ]
