# Generated by Django 5.2.17 on 2026-09-28 06:21

import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_gallerycategory_gallerysection_galleryimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(blank=True, help_text='The file is renamed from the category and title (e.g. gallery/labs/discovery-in-practice). Large photos are compressed automatically.', null=True, upload_to=website.models.gallery_upload_to),
        ),
    ]
