# Generated by Django 5.2.17 on 2026-09-28 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_galleryimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eyebrow', models.CharField(blank=True, help_text='e.g. "APPLY TO GTU"', max_length=100, verbose_name='Small heading')),
                ('title', models.TextField(help_text='Press Enter to start a new line.', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('name_label', models.CharField(default='Full Name', max_length=60)),
                ('name_placeholder', models.CharField(blank=True, max_length=100)),
                ('email_label', models.CharField(default='Email Address', max_length=60)),
                ('email_placeholder', models.CharField(blank=True, max_length=100)),
                ('phone_label', models.CharField(default='Phone Number', max_length=60)),
                ('phone_placeholder', models.CharField(blank=True, max_length=100)),
                ('program_label', models.CharField(default='Program of Interest', max_length=60)),
                ('program_placeholder', models.CharField(blank=True, help_text='First (empty) option of the dropdown.', max_length=100)),
                ('qualification_label', models.CharField(default='Highest Qualification', max_length=60)),
                ('qualification_placeholder', models.CharField(blank=True, max_length=100)),
                ('year_label', models.CharField(default='Year of Passing', max_length=60)),
                ('year_placeholder', models.CharField(blank=True, max_length=100)),
                ('goals_label', models.CharField(default='Tell us about your goals', max_length=60)),
                ('goals_placeholder', models.CharField(blank=True, max_length=200)),
                ('consent_text', models.CharField(blank=True, max_length=200)),
                ('submit_text', models.CharField(default='Submit Application', max_length=50, verbose_name='Submit button text')),
                ('success_message', models.CharField(help_text='Shown to the visitor after a successful submit.', max_length=300)),
                ('send_confirmation_email', models.BooleanField(default=True, help_text='Email the applicant an acknowledgement.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Apply Section (application form)',
                'verbose_name_plural': 'Apply Section (application form)',
            },
        ),
        migrations.CreateModel(
            name='ContactSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eyebrow', models.CharField(blank=True, help_text='e.g. "GET IN TOUCH"', max_length=100, verbose_name='Small heading')),
                ('title', models.TextField(help_text='Press Enter to start a new line.', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('show_contact_details', models.BooleanField(default=True, help_text='Show address, email and phone (from Site Settings).')),
                ('background_image', models.ImageField(blank=True, help_text='Shown behind a blue overlay. Recommended 1920×1080.', null=True, upload_to='contact/')),
                ('name_placeholder', models.CharField(default='Name', max_length=60)),
                ('email_placeholder', models.CharField(default='Email', max_length=60)),
                ('phone_placeholder', models.CharField(default='Phone', max_length=60)),
                ('subject_placeholder', models.CharField(default='Select Subject', help_text='First (empty) option of the subject dropdown.', max_length=60)),
                ('message_placeholder', models.CharField(default='Message', max_length=100)),
                ('submit_text', models.CharField(default='Send Message', max_length=50, verbose_name='Submit button text')),
                ('success_message', models.CharField(help_text='Shown to the visitor after a successful submit.', max_length=300)),
                ('send_confirmation_email', models.BooleanField(default=True, help_text='Email the visitor an acknowledgement.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Contact Section (contact form)',
                'verbose_name_plural': 'Contact Section (contact form)',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('program_name', models.CharField(blank=True, help_text='Program title at the time of applying (kept even if the course is deleted).', max_length=150)),
                ('qualification', models.CharField(max_length=120, verbose_name='Highest qualification')),
                ('year_of_passing', models.PositiveSmallIntegerField()),
                ('goals', models.TextField(blank=True)),
                ('consent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('in_review', 'In review'), ('admitted', 'Admitted'), ('not_admitted', 'Not admitted')], default='new', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Only visible in admin.', verbose_name='Internal notes')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='website.courseopening')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications (submitted)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplyPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first. Leave 0 to add at the end.')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to hide on the website.')),
                ('text', models.CharField(max_length=150)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='website.applysection')),
            ],
            options={
                'verbose_name': 'Point',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first. Leave 0 to add at the end.')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to hide on the website.')),
                ('name', models.CharField(max_length=80)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='website.contactsection')),
            ],
            options={
                'verbose_name': 'Subject option',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('subject_name', models.CharField(blank=True, help_text='Subject at the time of sending (kept even if the option is deleted).', max_length=80)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('replied', 'Replied'), ('closed', 'Closed')], default='new', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Only visible in admin.', verbose_name='Internal notes')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='website.contactsubject')),
            ],
            options={
                'verbose_name': 'Contact message',
                'verbose_name_plural': 'Contact messages (submitted)',
                'ordering': ['-created_at'],
            },
        ),
    ]
