# Generated by Django 5.2.17 on 2026-09-28 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_applysection_contactsection_application_applypoint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CtaSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('badge', models.CharField(blank=True, help_text='Yellow badge, e.g. "ADMISSIONS CYCLE 2026–27"', max_length=60)),
                ('title', models.TextField(help_text='Press Enter to start a new line.', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('primary_button_text', models.CharField(blank=True, max_length=50, verbose_name='Yellow button text')),
                ('primary_button_link', models.CharField(blank=True, max_length=255, verbose_name='Yellow button link')),
                ('secondary_button_text', models.CharField(blank=True, max_length=50, verbose_name='White button text')),
                ('secondary_button_link', models.CharField(blank=True, max_length=255, verbose_name='White button link')),
                ('background_image', models.ImageField(blank=True, help_text='Shown behind a blue overlay. Recommended 1920×1080.', null=True, upload_to='cta/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'CTA Banner (Your Future Starts Here)',
                'verbose_name_plural': 'CTA Banner (Your Future Starts Here)',
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logo', models.ImageField(blank=True, help_text='Optional. Leave empty to use the logo from Site Settings.', null=True, upload_to='branding/')),
                ('name', models.CharField(blank=True, help_text='Leave empty to use the university name from Site Settings.', max_length=100)),
                ('tagline', models.CharField(blank=True, help_text='e.g. "ESTABLISHED 2001 • COIMBATORE"', max_length=100)),
                ('about_text', models.TextField(blank=True)),
                ('show_contact_details', models.BooleanField(default=True)),
                ('address_label', models.CharField(default='Campus:', max_length=30)),
                ('phone_label', models.CharField(default='Telephone:', max_length=30)),
                ('email_label', models.CharField(default='Email:', max_length=30)),
                ('quick_links_heading', models.CharField(default='Quick Links', max_length=60)),
                ('programs_heading', models.CharField(default='Academic Programs', max_length=60)),
                ('channels_heading', models.CharField(default='Official Channels', max_length=60)),
                ('channels_text', models.TextField(blank=True, help_text='Text above the social media icons.')),
                ('office_title', models.CharField(blank=True, max_length=100)),
                ('office_hours', models.CharField(blank=True, max_length=150)),
                ('copyright_text', models.CharField(blank=True, help_text='Use {year} for the current year, e.g. "© {year} Global Tamil University. All Rights Reserved."', max_length=200)),
            ],
            options={
                'verbose_name': 'Footer',
                'verbose_name_plural': 'Footer',
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first. Leave 0 to add at the end.')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to hide on the website.')),
                ('column', models.CharField(choices=[('quick', 'Quick Links'), ('programs', 'Academic Programs'), ('legal', 'Bottom bar (legal)')], max_length=20)),
                ('label', models.CharField(max_length=100)),
                ('link', models.CharField(help_text='Section anchor like #about, or a full URL.', max_length=255)),
                ('open_in_new_tab', models.BooleanField(default=False)),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='website.footer')),
            ],
            options={
                'verbose_name': 'Footer link',
                'ordering': ['column', 'order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LegalLink',
            fields=[
            ],
            options={
                'verbose_name': 'Bottom bar link',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.footerlink',),
        ),
        migrations.CreateModel(
            name='ProgramLink',
            fields=[
            ],
            options={
                'verbose_name': 'Academic program link',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.footerlink',),
        ),
        migrations.CreateModel(
            name='QuickLink',
            fields=[
            ],
            options={
                'verbose_name': 'Quick link',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.footerlink',),
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first. Leave 0 to add at the end.')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to hide on the website.')),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('linkedin', 'LinkedIn'), ('twitter', 'X / Twitter'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('url', models.URLField(blank=True, help_text='Full profile/channel URL. Icons without a URL are hidden.')),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='website.footer')),
            ],
            options={
                'verbose_name': 'Social media link',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
