# Generated by Django 5.2.17 on 2026-09-28 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_ctasection_footer_footerlink_legallink_programlink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutfeature',
            name='icon_class',
            field=models.CharField(blank=True, help_text='Outline icon name: graduation-cap, book-open, library, briefcase, school, microscope — or any Font Awesome class, e.g. "fa-solid fa-flask" (fontawesome.com/icons).', max_length=100),
        ),
        migrations.AlterField(
            model_name='program',
            name='icon_class',
            field=models.CharField(blank=True, help_text='Outline icon name: graduation-cap, book-open, library, briefcase, school, microscope — or any Font Awesome class, e.g. "fa-solid fa-flask" (fontawesome.com/icons).', max_length=100),
        ),
    ]
