# Generated by Django 5.2.17 on 2026-09-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_aboutfeature_icon_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='url',
            field=models.URLField(blank=True, help_text='Full profile/channel URL. Without a URL the icon is shown but not clickable.'),
        ),
    ]
