# Generated by Django 5.2.17 on 2026-09-29 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_sociallink_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eyebrow', models.CharField(blank=True, help_text='e.g. "FAQ"', max_length=100, verbose_name='Small heading')),
                ('title', models.TextField(help_text='Press Enter to start a new line.', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ Section',
                'verbose_name_plural': 'FAQ Section',
            },
        ),
        migrations.CreateModel(
            name='FaqItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first. Leave 0 to add at the end.')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to hide on the website.')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='website.faqsection')),
            ],
            options={
                'verbose_name': 'Question',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
